kind: pipeline
name: default

clone:
  depth: 50

steps:
- name: api
  image: docker
  environment:
    DOCKER_REPO: 
      from_secret: docker_repo
    DOCKER_USERNAME: 
      from_secret: docker_username
    DOCKER_PASSWORD: 
      from_secret: docker_password
    DOCKER_REGISTRY: 
      from_secret: docker_registry
  commands:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $DOCKER_REGISTRY
  - docker build --build-arg API_URL=$API_URL -t api:latest . 
  - docker tag api:latest $DOCKER_REGISTRY/api:latest
  - docker push $DOCKER_REGISTRY/api:latest    
  branches:
  - devops 
  - staging-v2
  volumes:
  - name: docker
    path: /var/run/docker.sock

- name: ssh
  image: appleboy/drone-ssh
  settings: 
    host: 
      from_secret: SSH_HOST
    username: 
      from_secret: SSH_USERNAME
    port: 22
    key: 
      from_secret: SSH_KEY
    script:
      - cd SME-plataforma-curriculo
      - chmod +x full_deploy.sh
      - ./full_deploy.sh
  branches:
  - devops 
  - staging-v2

volumes:
- name: docker
  host:
    path: /var/run/docker.sock