AllCops:
  Exclude:
    - 'Rakefile'
    - 'Gemfile'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/*'
    - 'spec/**/*'
Metrics/ClassLength:
  Max: 1500

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context', 'register']